### ISSUE TITLE
XGBoost traindistributedgpu exception

### ISSUE THREAD

**Issue by caroljmcdonald** [NVIDIA/spark-xgboost-examples#19]
I tried running the example https://github.com/NVIDIA/spark-xgboost-examples/blob/spark-3/examples/notebooks/scala/taxi-gpu.ipynb .  After following the instructions to set up on a Databricks cluster 7.0 ML with GPUs,  I got the following exception when calling xgbRegressor.fit(trainSet)

at ml.dmlc.xgboost4j.scala.spark.XGBoost$.postTrackerReturnProcessing(XGBoost.scala:848)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.$anonfun$trainDistributedPreferGpu$1(XGBoost.scala:656)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.$anonfun$trainDistributedPreferGpu$1$adapted(XGBoost.scala:636)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.immutable.List.map(List.scala:298)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributedPreferGpu(XGBoost.scala:635)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostRegressor.trainHonorGpu(XGBoostRegressor.scala:257)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostRegressor.trainGpu(XGBoostRegressor.scala:196)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostRegressor.fit(XGBoostRegressor.scala:204)
	at line4c05786d06ce4af79d5461b86d74659149.$read$$iw$$iw$$iw$$iw$$iw$$iw.$anonfun$model$1(command-3584891357336110:4)
	at line4c05786d06ce4af79d5461b86d74659147.$read$$iw$$iw$$iw$$iw$$iw$$iw$Benchmark$.time(command-3584891357336108:5)
	at line4c05786d06ce4af79d5461b86d74659149.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-3584891357336110:4)
	at line4c05786d06ce4af79d5461b86d74659149.$read$$iw$$iw$$iw$$iw$$iw.<init>(command-3584891357336110:55)
	at line4c05786d06ce4af79d5461b86d74659149.$read$$iw$$iw$$iw$$iw.<init>(command-3584891357336110:57)
	at line4c05786d06ce4af79d5461b86d74659149.$read$$iw$$iw$$iw.<init>(command-3584891357336110:59)
	at line4c05786d06ce4af79d5461b86d74659149.$read$$iw$$iw.<init>(command-3584891357336110:61)
	at line4c05786d06ce4af79d5461b86d74659149.$read$$iw.<init>(command-3584891357336110:63)
	at line4c05786d06ce4af79d5461b86d74659149.$read.<init>(command-3584891357336110:65)
	at line4c05786d06ce4af79d5461b86d74659149.$read$.<init>(command-3584891357336110:69)
	at line4c05786d06ce4af79d5461b86d74659149.$read$.<clinit>(command-3584891357336110)
	at line4c05786d06ce4af79d5461b86d74659149.$eval$.$print$lzycompute(<notebook>:7)
	at line4c05786d06ce4af79d5461b86d74659149.$eval$.$print(<notebook>:6)
	at line4c05786d06ce4af79d5461b86d74659149.$eval.$print(<notebook>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:745)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1021)
	at scala.tools.nsc.interpreter.IMain.$anonfun$interpret$1(IMain.scala:574)
	at scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:41)
	at scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:37)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:41)
	at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:573)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:600)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:570)
	at com.databricks.backend.daemon.driver.DriverILoop.execute(DriverILoop.scala:215)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.$anonfun$repl$1(ScalaDriverLocal.scala:202)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExitInternal$.trapExit(DriverLocal.scala:714)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExit$.apply(DriverLocal.scala:667)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.repl(ScalaDriverLocal.scala:202)
	at com.databricks.backend.daemon.driver.DriverLocal.$anonfun$execute$10(DriverLocal.scala:396)
	at com.databricks.logging.UsageLogging.$anonfun$withAttributionContext$1(UsageLogging.scala:238)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at com.databricks.logging.UsageLogging.withAttributionContext(UsageLogging.scala:233)
	at com.databricks.logging.UsageLogging.withAttributionContext$(UsageLogging.scala:230)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionContext(DriverLocal.scala:49)
	at com.databricks.logging.UsageLogging.withAttributionTags(UsageLogging.scala:275)
	at com.databricks.logging.UsageLogging.withAttributionTags$(UsageLogging.scala:268)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionTags(DriverLocal.scala:49)
	at com.databricks.backend.daemon.driver.DriverLocal.execute(DriverLocal.scala:373)
	at com.databricks.backend.daemon.driver.DriverWrapper.$anonfun$tryExecutingCommand$1(DriverWrapper.scala:653)
	at scala.util.Try$.apply(Try.scala:213)
	at com.databricks.backend.daemon.driver.DriverWrapper.tryExecutingCommand(DriverWrapper.scala:645)
	at com.databricks.backend.daemon.driver.DriverWrapper.getCommandOutputAndError(DriverWrapper.scala:486)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommand(DriverWrapper.scala:598)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInnerLoop(DriverWrapper.scala:391)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInner(DriverWrapper.scala:337)
	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:219)
	at java.lang.Thread.run(Thread.java:748)
Command took 9.03 seconds -- by carolm@nvidia.com at 8/4/2020, 4:01:59 PM on carol

**Comment by wbo4958** [comment]
Hi @caroljmcdonald,

Seems the training process failed. but we may need the executor exception to check.
Or @wjxiz1992, Have you run on Databricks cluster 7.0 ML with GPUs successfully?

**Comment by caroljmcdonald** [comment]
Here is some more information , this prints out
sc.listJars.foreach(println)
val xgbClassifier = new XGBoostClassifier(xgbParamFinal)
      .setLabelCol(labelColName)
      .setFeaturesCols(featureNames)
val c = xgbClassifier.getClass()
val codeSource = c.getProtectionDomain().getCodeSource();
if ( codeSource != null) {
  System.out.println(codeSource.getLocation());
}
--------------------

spark://10.59.251.250:37631/jars/addedFile3690476365086304709xgboost4j_spark_3_0_1_0_0_0_1_0-0c8d0.jar
file:/databricks/jars/spark--maven-trees--ml--7.x--xgboost--ml.dmlc--xgboost4j-spark_2.12--ml.dmlc__xgboost4j-spark_2.12__1.0.0.jar

xgbClassifier: ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier = xgbc_315a65e980bf
c: Class[_ <: ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier] = class ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier
codeSource: java.security.CodeSource = (file:/databricks/jars/spark--maven-trees--ml--7.x--xgboost--ml.dmlc--xgboost4j-spark_2.12--ml.dmlc__xgboost4j-spark_2.12__1.0.0.jar <no signer certificates>)

**Comment by wjxiz1992** [comment]
Hi @caroljmcdonald , I updated the get-started-doc, can you add 2 more line in cluster-spark-properties and rerun the job? https://github.com/NVIDIA/spark-xgboost-examples/pull/20

**Comment by caroljmcdonald** [comment]
yes, which 2 lines ?

**Comment by wjxiz1992** [comment]
```
    spark.plugins com.nvidia.spark.SQLPlugin
    spark.rapids.memory.gpu.pooling.enabled false
```
The PR is still in review, https://github.com/NVIDIA/spark-xgboost-examples/pull/20. But you can have a try. @caroljmcdonald

**Comment by caroljmcdonald** [comment]
thanks! that worked

**Comment by wbo4958** [comment]
Thx @caroljmcdonald, Close this issue
